name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone schemata-go
        run: git clone https://github.com/nostrability/schemata-go.git ../schemata-go

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - run: go mod edit -replace github.com/nostrability/schemata-go=../schemata-go
      - run: go mod tidy
      - run: go test ./...
